### ISSUE TITLE
Record command doesn't work after updating therubyracer

### ISSUE THREAD

**Issue by waj** [instedd/verboice#264]
Record command is failing after updating therubyracer gem to 0.11.0beta1 

Stacktrace:

{{{
Exception NoMethodError: undefined method `to_i' for [object global]:V8::Object /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/object.rb:55:in`method_missing' /Users/aromero/Documents/Projects/verboice/app/models/session.rb:172:in `record_url' /Users/aromero/Documents/Projects/verboice/app/models/session.rb:141:in`block in new_v8_context' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/access/invocation.rb:16:in `call' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/access/invocation.rb:16:in`methodcall' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/access/invocation.rb:4:in `methodcall' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/conversion/code.rb:33:in`block in call' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/error/protect.rb:4:in `protect' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/conversion/code.rb:23:in`call' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:28:in `Run' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:28:in`block (2 levels) in eval' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/error/try.rb:6:in `block in try' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/error/try.rb:5:in`call' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/error/try.rb:5:in `TryCatch' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/error/try.rb:5:in`try' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:28:in `block in eval' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:102:in`block (2 levels) in lock_scope_and_enter' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:99:in `call' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:99:in`HandleScope' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:99:in `block in lock_scope_and_enter' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:98:in`call' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:98:in `Locker' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:98:in`lock_scope_and_enter' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:77:in `enter' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/gems/therubyracer-0.11.0beta1/lib/v8/context.rb:26:in`eval' /Users/aromero/Documents/Projects/verboice/app/models/session.rb:66:in `eval' /Users/aromero/Documents/Projects/verboice/app/models/commands/trace_command.rb:34:in`run' /Users/aromero/Documents/Projects/verboice/app/models/session.rb:124:in `run_command' /Users/aromero/Documents/Projects/verboice/app/models/session.rb:82:in`block in run' /Users/aromero/Documents/Projects/verboice/app/models/session.rb:80:in `loop' /Users/aromero/Documents/Projects/verboice/app/models/session.rb:80:in`run' /Users/aromero/Documents/Projects/verboice/app/models/base_broker.rb:115:in `accept_call' /Users/aromero/Documents/Projects/verboice/app/models/asterisk/call_manager.rb:30:in`agi_post_init' /Users/aromero/.rvm/gems/ruby-1.9.3-rc1@verboice/bundler/gems/batphone-6475f47d4d44/lib/batphone/fibered_fast_agi_protocol.rb:9:in `block in agi_post_init'
}}}

---
- Imported from BitBucket: https://bitbucket.org/instedd/verboice/issue/264
- Originally Reported By: Adrian Romero
- Originally Created At: 2012-06-27 20:10:52+00:00
